name = "Ray Tracing"
packages = ["plyfile>=1.1.3"]

[files]
"./libthree.py" = ""

[js_modules.main]
"https://unpkg.com/three@v0.149.0/build/three.module.js" = "three"
"https://unpkg.com/three@v0.149.0/examples/jsm/controls/TrackballControls.js" = "tc"
"https://cdnjs.cloudflare.com/ajax/libs/stats.js/r17/Stats.min.js" = "stats"
